---
title: "상대론적 역학"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

## 최소작용의 원리

### 자유입자의 최소작용 {#sec-CFT_least_action_on_free_particle}

자유 입자의 액션 적분 $S$ 를 결정하기 위해 반드시 만족해야 하는 조건은 적분값이 기준틀이 로런츠 변환에 대해 불변이어야 한다는 것이다. 즉 $S$ 는 $4$-스칼라 이어야 한다. 또한 적분되는 양은 1차 미분형식 이어야 한다. 그런데 자유 입자에 대해 우리가 얻을 수 있는 스칼라는 $ds$ (혹은 상수배인 $d\tau$) 뿐이며 따라서 자유입자에 대해 다음이 성립한다.

$$
S = - \alpha \int_a^b ds 
$$

우리는 @sec-CFT_proper_time_and_world_line 에서 $\int_a^b ds$ 의 최대값이 두 세계점 $a,\,b$ 를 잇는 4차원 직선임을 보았다. 따라서 일반적인 최소 작용의 원리의 이름에 부응하기 위해서는 $\alpha >0$ 이어야 한다. 일반적으로 작용(action) 은

$$
S=\int_{t_1}^{t_2} L\,dt
$$

로 정의되며 $L$ 을 라그랑지안이라고 하므로 4차원 시공간의 자유입자에 대한 라그랑지안은 아래와 같이 정할 수 있다.

$$
L = -\alpha c \sqrt{1-\dfrac{v^2}{c^2}}.
$$

이것을 $v\ll c$ 에 대해 근사하면

$$
L = -\alpha c + \dfrac{\alpha v^2}{2c}
$$

이다. 우리는 고전역학에서 자유입자의 라그랑지안 $L_\text{cl}= \dfrac{mv^2}{2}$ 임을 안다. 따라서 $\alpha = mc$ 로 놓으면 4차원 시공간에서 자유입자의 액션 적분은

$$
S=-mc\int_a^b ds.
$$ {#eq-CFT_action_integral_of_4d_free_particle}

이며 라그랑지안은 아래와 같다.

$$
L = -mc^2\sqrt{1-\dfrac{v^2}{c^2}}.
$$ {#eq-CFT_lagrangian_of_4d_free_particle}

</br>

## 에너지와 운동량

### 자유 입자의 에너지와 운동량 {#sec-CFT_energy_and_momentum_of_single_free_particle}

#### **단일 입자의 경우**

라그랑지안이 주어졌을 때 입자의 운동량을 고전역학적으로 계산하면 아래와 같다.

$$
\bf{p} = \dfrac{\partial L}{\partial \bf{v}}= \dfrac{m\bf{v}}{\sqrt{1-v^2/c^2}}.
$$ {#eq-CFT_relativistic_momentum}

이 때 에너지 함수 $\mathcal{E} = \bf{p\cdot v}-L$ 로부터

$$
\mathcal{E}=\bf{p\cdot v} -L = \dfrac{mc^2}{\sqrt{1-v^2/c^2}}
$$ {#eq-CFT_relativistic_energy}

임을 안다. $v=0$ 일 때의 에너지 $\mathcal{E}=mc^2$ 를 입자의 **정지 에너지 (rest energy)** 라고 한다. 또한 $v\ll c$ 일 때

$$
\mathcal{E}\approx mc^2 + \dfrac{mv^2}{2}
$$

인데, 이는 고전역학적인 운동에너지에 정지 에너지를 합친 값으로 입자에 대해 상수인 정지 에너지 항을 제외하면 고전역학에 잘 근사된다는 것을 알 수 있다. 

</br>

#### **정지한 입자계의 경우**

여러 입자로 이루어진 정지한 물체의 에너지는 각각의 개별 입자의 정지 에너지와 입자들 사이에 작용하는 상호작용 에너지의 합이다. 즉 $Mc^2 \ne \sum_a m_a c^2$ 이며 따라서 $M \ne \sum_a m_a$ 이다. 다시말하면 상대론에서는 질량 보존의 법칙의 성립하지 않으며 전체 질량은 부분 질량의 합과 다르다. 

</br>

### 운동량과 에너지 {#sec-CFT_momentum_and_energy}

@eq-CFT_relativistic_momentum 와 @eq-CFT_relativistic_energy 로 부터 다음의 관계를 얻는다.

$$
\mathcal{E}= p^2c^2  + m^2c^4.
$$ {#eq-CFT_energy_and_momentum_relation_for_free_particle}

운동량의 함수로 표현된 에너지를 해밀토니안 함수라고한다. 즉 자유 입자의 해밀토니안 $\mathscr{H}$ 는 아래와 같다.

$$
\mathcal{H}= c\sqrt{p^2+m^2c^2}.
$$ {#eq-CFT_energy_and_momentum_relation_for_free_particle}

고전역학적 근사 즉 $v\ll c$ 에 대해

$$
\mathcal{H}= mc^2 + \dfrac{p^2}{2m}
$$

가 성립하며 이는 정지 에너지를 제외하면 고전역학과 동일하다. 또한 @eq-CFT_relativistic_momentum 와 @eq-CFT_relativistic_energy 로 부터 아래의 관계를 얻을 수 있다.

$$
\bf{p} = \mathcal{E}\dfrac{\bf{v}}{c^2}.
$$ {#eq-CFT_relation_of_free_particls_between_momentum_velocity_and_energy}

$v = c$ 이면 에너지와 운동량이 무한히 커지게 되는데 이는 질량을 가진 입자가 빛의 속도로 운동할 수 없다는 의미이다. 물론 질량이 없는 입자의 경우는 빛의 속도로 움직인다. 이 경우 

$$
P = \dfrac{\mathcal{E}}{c}
$$ {#eq-CFT_relation_of_energy_and_momentum_of_massless_particle}

로 쓸 수 있다. 이것은 질량이 있으며 입자의 에너지 $\mathcal{E}$ 가 정지 질량에 비해 매우 클때 근사적으로 사용 할 수 있다.

</br>

### 4-운동량 {#sec-CFT_4_momentum}

이제 운동량과 에너지의 4차원 형식에 대해 알아보자. 최소작용의 원리는 아래와 같이 쓸 수 있다.

$$
\delta S = -mc \, \delta \left(\int_a^b \,ds\right) = 0.
$$

$ds=\sqrt{dx_\mu dx^\mu}$ 이므로 4-속도 @eq-CFT_defintion_of_4_velocity 를 이용하면

$$
\delta S = -mc \int_a^b \dfrac{dx_\mu \delta dx^\mu}{ds} = -mc \int_a^b u_\mu d\delta x^\mu 
$$

이며, 부분적분을 통해 다음을 얻는다.

$$
\delta S = - mcu_\mu \delta x^\mu {\Large |}_{a}^b + mc \int_a^b \delta x^\mu \dfrac{du_\mu}{ds}\,ds.
$$ {#eq-CFT_delta_S_equal_to_0}

고전역학의 변분법에서와 같이 세계점 $a,\,b$ 를 고정시키면 $\delta x^\mu(a) = \delta x^\mu (b) = 0$ 이며 따라서 

$$
\dfrac{du_\mu}{ds}=0
$$

을 얻는다. 즉 우리는 4차원 자유 입자의 운동방정식을 얻었다. 


이제 @eq-CFT_delta_S_equal_to_0 에서 시작하는 세계점을 고정시키고 위의 운동방정식을 만족시킬 때를 알아보자. 그렇다면 

$$
\delta S = -mcu_\mu \delta x^\mu
$$

이다. 여기서 우리는 고전역학에서와 같이 액선 적분 $S$ 에 대한 편미분으로 **4-운동량 (4-momentum)** 을 정의 할 수 있다.

$$
\begin{aligned}
p_\mu &:= - \dfrac{\partial S}{\partial x^\mu} = \left(\dfrac{\mathcal{E}}{c},\, -\bf{p} \right), \\
\end{aligned}
$$ {#eq-CFT_definition_of_covariant_4_momentum}

위의 공변 4-운동량과 같은 방법으로 반변 4-운동량 벡터를 정할 수 있다. 즉 

$$
p^\mu = mcu^\mu = \left(\dfrac{\mathcal{E}}{c},\, \bf{p} \right).
$${#eq-CFT_definition_of_contravariant_4_momentum}

즉 상대론에서는 에너지와 운동량이 단일한 4-벡터를 구성하며 이로부터 4-운동량 역시 로런츠 변환을 따른다는 것을 알 수 있다. 또한 $u_\mu u^\mu = 1$ 로 부터

$$
p_\mu p^\mu = m^2c^2
$$ {#eq-CFT_square_sum_of_4_momentum}

임을 안다. 고전역학에서와 마찬가지로 4-힘 $F^\mu$ 를 아래와 같이 정의 할 수 있다.

$$
F^\mu := \dfrac{dp^\mu}{ds}= mc \dfrac{du^\mu}{ds}.
$$ {#eq-CFT_4_force}

위 식의 정확한 표현에 대해서는 @exr-CFT_4_force 을 보라. 또한 상대론적 해밀턴-야코비 방정식은 @eq-CFT_square_sum_of_4_momentum 에서 $p_\mu$ 를 $-\partial S/\partial x^i$ 로 교체하여 얻을 수 있다. 

$$
\dfrac{\partial S}{\partial x_\mu}\dfrac{\partial S}{\partial x^\mu} = g^{\mu \nu}\dfrac{\partial S}{\partial x^\mu}\dfrac{\partial S}{\partial x^\nu} = m^2c^2.
$$ {#eq-CFT_relativistic_hamilton_jacobi_equation}

</br>

### 연습문제 {.unnumbered}


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CFT_4_force}

$\bf{F}= \dfrac{d\bf{p}}{dt}$ 를 이용하여 4-힘 (@eq-CFT_4_force) 을 표현하라.

:::

</div>

::: {.solution}

$\dot{\bf{v}}= d\bf{v}/dt$ 와 $\bf{f}=d\bf{p}/dt$ 에 대해 우선 $\bf{f\cdot v}$ 를 계산하자.

$$
\begin{aligned}
\bf{f\cdot v}&=\dfrac{d\bf{p}}{dt} \cdot \bf{v} = \left[\dfrac{d}{dt}\left(\dfrac{m\bf{v}}{\sqrt{1-v^2/c^2}}\right)\right] \bf{\cdot v} \\[0.3em]
&=\left[\dfrac{m(\bf{v \cdot}\dot{\bf{v}})v^2}{c^2(1-v^2/c^2)^{3/2}} + \dfrac{m(\bf{v \cdot}\dot{\bf{v}})}{\sqrt{1-v^2/c^2}}\right] \\[0.3em]
&= \dfrac{m(\bf{v \cdot}\dot{\bf{v}})}{(1-v^2/c^2)^{3/2}}
\end{aligned}
$$

$$
\begin{aligned}
F^0 &= \dfrac{m}{\sqrt{1-v^2/c^2}} \dfrac{d}{dt}\left(\dfrac{1}{\sqrt{1-v^2/c^2}}\right) = \dfrac{m}{c^2} \dfrac{\bf{v\cdot}\dot{\bf{v}}}{(1-v^2/c^2)^2}\\[0.3em]
&=\dfrac{\bf{f\cdot \bf{v}}}{c^2 \sqrt{1-v^2/c^2}} \\[0.3em]
F^i &=\dfrac{m}{\sqrt{1-v^2/c^2}} \dfrac{d}{dt}\left(\dfrac{v^i}{\sqrt{1-v^2/c^2}}\right) = \dfrac{f^i}{c \sqrt{1-v^2/c^2}}.
\end{aligned}
$$


:::